config/routes.rb
Flow::Application.routes.draw do |map|

  
  

  
  
  root :to => "entries#index"
  match 'login'  => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  
  rule = { :year => /(19|20)\d\d/, :month => /[01]\d/ }
  match "/entries/:year/:month/:slug", :to => "entries#show",
    :constraints => rule
  match "/entries(/:year(/:month(/:slug)))", :to => "entries#index",
    :constraints => rule
  
  resources :entries
  resource :session
  
  namespace :admin do
    resources :entries
  end
  
  match "feed" => "entries#index", :format => 'atom', :as => :feed
  
  

end

app/models/author.rb
# http://www.railstutorial.org/chapters/modeling-and-viewing-users-two
# http://mongoid.org/docs/callbacks

require "digest"
class Author
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name
  field :salt
  field :encrypted_password
  
  validates_presence_of :name, :password
  validates_uniqueness_of :name
  
  before_save :encrypt_password!
  
  def encrypt_password!
    self.salt!
    self.encrypted_password = self.class.hash("#{salt}#{password}")
    self
  end
  
  def salt!
    self.salt = self.class.hash "#{Time.now.utc}#{password}"
  end
  
  def has_password?(plain_password)
    encrypted_password == self.class.hash("#{salt}#{plain_password}")
  end
  
  class << self
    def authenticate(params)
      return nil unless params[:name] && params[:password]
      a = Author.first :conditions => {:name=>params[:name]}
      a && a.has_password?(params[:password]) ? a : nil
    end
    
    def hash(str)
      Digest::SHA2.hexdigest(str)
    end
  end
end

app/models/entries.rb
class Entry
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :title
  field :slug
  field :body
  
  # will-paginate
  cattr_reader :per_page
  @@per_page = 2
  
  class << self
  end
  
  def posted
    created_at("")
  end
  
  def html
    body
  end
end

app/models/entry.rb
require 'will_paginate/finders/base'
require "uri"

class Entry
  include Mongoid::Document
  include Mongoid::Timestamps
    
  field :title
  field :slug
  field :body
  field :published_at, :type => DateTime
  
  validates_presence_of :title, :body
  
  # will-paginate
  include WillPaginate::Finders::Base
  cattr_reader :per_page
  @@per_page = 2
  
  before_save :compat_slug!
  
  def compat_slug!
    self.slug = self.class.make_slug(title) if ! slug || slug.empty?
    self.slug = URI.escape slug
  end
  
  def publish(time=nil)
    self.published_at = (time || Time.now).utc
    self
  end
  def unpublish
    self.published_at = nil
    self
  end
  def published?
    ! published_at.nil?
  end
  def draft?
    published_at.nil?
  end
  
  class << self
    def make_slug(source)
      source.gsub(/[^a-zA-Z0-9\s]/,"").downcase.gsub(/\s/, '-')
    end
    
    #
    # query
    #
    def published
      criteria.where(:published_at.ne => nil).order_by([:published_at, :desc])
    end
    
    def draft
      criteria.where(:published_at => nil).order_by([:created_at, :desc])
    end
    
    def ranged(p)
      now = Time.now
      time = [p[:year] || now.year, p[:month] || now.month, now.day].join('-').to_time
      period = p[:month] ? :month : :year
      
      criteria.and(
        :published_at => {"$gte" => time.send("beginning_of_#{period}").utc,
          "$lte" => time.send("end_of_#{period}").utc }
      )
    end
    
    def by_params(p)
      q = ranged(p)
      q = q.criteria.where(:slug => p[:slug]) if p[:slug]
      q
    end
  end
  
  def posted
    published_at("")
  end
  
  def html
    body
  end
end

app/controllers/admin/entries_controller.rb
class Admin::EntriesController < ApplicationController
  before_filter :require_authentication
  
  respond_to :html, :xml, :json
  
  def index
    @entries = entry.draft.by_params(params).paginate(
      :page => (params[:page] || 1), :per_page => Entry.per_page)
    render :template => 'entries/index'
  end
  
  def new
    @entry = entry.new
  end
  
  def create
    attrs = params[:entry]
    
    @entry = entry.create attrs    
    case
      when @entry.published? && attrs[:published_at] == '0'; @entry.unpublish
      when @entry.draft? && attrs[:published_at] == '1'; @entry.publish
    end
    @entry.save!
    
    flash[:notice] = 'created'
    redirect_to edit_admin_entry_path(@entry)
  end
  
  def edit
    @entry = entry.first(:conditions=>{:id => params[:id]})
    render_404 unless @entry
  end
  
  def update
    @entry = entry.first(:conditions=>{:id => params[:id]})
    render_404 unless @entry
    
    attrs = params[:entry]
    case
      when @entry.published? && attrs[:published_at] == '0'; @entry.unpublish
      when @entry.draft? && attrs[:published_at] == '1'; @entry.publish
    end
    attrs.delete :published_at
    
    @entry.update_attributes! attrs
    render :template => 'admin/entries/edit'
  end
  
  def destroy
    @entry = entry.first(:conditions=>{:id => params[:id]})
    render_404 unless @entry
    
    @entry.delete
    flash[:notice] = "deleted"
    redirect_to admin_entries_path
  end
  
  private
  def entry
    Entry
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    
  before_filter :set_defaults
  attr_accessor :page_title
  
  layout proc{ |r| "default"
    # r.request.request_uri.index(/admin/) ? "admin" : "default" 
  }
  
  protected
  def render_404(exception = nil)
    if exception
      logger.info "Rendering 404 with exception: #{exception.message}"
    end

    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404.html", :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end
  
  def set_defaults
    page_title = "blog"
  end
  
  # Auth
  def require_authentication
    do_authenticate unless logged_in?
  end
  def logged_in?
    authenticated?
  end
  def do_authenticate
    authenticate!
  end
  
  # def require_basic_auth
  #   authenticate_or_request_with_http_basic do |name, password|
  #     path = File.join(Rails.root, 'secret.json')
  #     File.exists?(path) && password == JSON.parse(File.read(path))['password']
  #   end
  # end  
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  respond_to :html, :xml, :json, :atom

  def index
    @entries = entry.by_params(params).paginate(
      :page => (params[:page] || 1), :per_page => Entry.per_page)
    @updated_at = @entries.size > 0 ? @entries.first.published_at : nil
    
    respond_with @entries
  end
  
  def show
    @entry = entry.by_params(params).first
    
    unless @entry
      render_404 unless @entry
    else
      respond_with @entry
    end
  end
  
  private
  def entry
    Entry.published
  end
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController

  def index
    period = case
      when params[:dd] then 'date'
      when params[:mm] then 'month'
      when params[:yyyy] then 'year'
      else nil end
    pnum = params[:page] || 1
    
    @entries = if period
      time = time_of params
      Entry.list.between(
        time.send("beginning_of_#{period}"), time.send("end_of_#{period}")
      ).paginate :page=>pnum, :per_page=>Entry.per_page
    else
      Entry.list.paginate(:page => pnum, :per_page => Entry.per_page)
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @entries }
    end
  end

  def show
    raise Exception.new("hoge")
  end
  
  private
  def time_of(params)
    now = Time.now
    [
      params[:yyyy] || now.year,
      params[:mm] || now.month,
      params[:dd] || now.day
    ].join('-').to_time
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def unauthenticated
    redirect_to new_session_path
  end
  
  def new
    if logged_in?
      flash[:notice] = "you already have logged in as "+user.name
      redirect_to :root
    end
  end
  
  def create
    do_authenticate
    
    if logged_in?
      redirect_to :root
    else
      flash[:notice] = "invalid name or password"
      redirect_to :new_session
    end
  end
  
  def destroy
    logout
    flash[:notice] = "logged out"
    redirect_to :new_session
  end
end

app/helpers/admin/entries_helper.rb
module Admin::EntriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entry_helper.rb
module EntryHelper
  # FIXME to be cool
  def entry_perm_path(entry)
    sprintf "/entries/%04d/%02d/%s", 
      entry.created_at.year, entry.created_at.month, entry.slug
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/entries/edit.html.haml
-form_for [:admin, @entry] do |f|
  .entry
    .title
      title
      = f.text_field :title
    .slug
      slug
      = f.text_field :slug    
    .body
      body
      = f.text_area :body
    .property
      published
      = f.check_box :published_at
      = @entry.published_at.to_s
    .submit
      = f.submit
    .attributes
      %ul
        %li 
          = @entry.created_at.to_s(:entry)

.delete
  = button_to "delete", admin_entry_path(@entry), :method => 'delete'

app/views/admin/entries/new.html.haml
-form_for [:admin, @entry] do |f|
  .entry
    .title
      title
      = f.text_field :title
    .slug
      slug
      = f.text_field :slug    
    .body
      body
      = f.text_area :body
    .property
      published
      = f.check_box :published_at
    .submit
      = f.submit

app/views/entries/_entry.html.haml
.post
  .date
    = entry.published_at.strftime '%b'
    %span.day= entry.published_at.strftime '%d'
    = entry.published_at.strftime '%Y'
    %a
  .regular
    %h3= link_to entry.title, entry_perm_path(entry)
    = entry.html
    - if authenticated?
      %ul.attributes
        %li= link_to 'edit', edit_admin_entry_path(entry)
    %p.notes_and_comment_count

app/views/entries/index.html.haml
= render @entries

=will_paginate @entries

app/views/entries/show.html.haml
= render :partial=> @entry

app/views/entry/index.html.haml
- for entry in @entries
  .entry
    %h2.title= entry.title
    .body= entry.html
    .attributes
      %ul
        %li 
          permlink entry
          = entry.created_at.to_s(:entry)

= will_paginate @entries

app/views/layouts/3col.html.haml
!!! html
%html
  %head
    %title= @page_title ||= 'sousk.net'
    %meta{"http-equiv" => "Content-Type", :content => "text/html;charset=utf-8"}
    
    / %link{'rel'=>"alternate", 'type'=>"application/atom+xml", 
    /   'title'=>"sousk.net - timeline", 'href'=> timeline_url }
    
    = stylesheet_link_tag "3col"
    / = stylesheet_link_tag "3col_debug"
    = stylesheet_link_tag "phi"
    
  %body
    #header
      %h1= @page_title ||= 'page title'

    .colmask.blogstyle
      .colmid
        .colleft
          .col1wrap
            .col1
              #messages
                #notice= flash[:notice]
                #error= flash[:error]
                #warn= flash[:warn]
              #contents
                = yield :layout

          .col2
            %h2 recent posts
            %ul
              - Entry.published.limit(8).each do |e|
                %li= link_to e.title, entry_perm_path(e)
          .col3
            

    #footer
      footer

app/views/layouts/default.html.haml
!!! html
%html
  %head
    %title= @page_title ||= 'sousk.net'
    %meta{"http-equiv" => "Content-Type", :content => "text/html;charset=utf-8"}
    
    %link{'rel'=>"alternate", 'type'=>"application/atom+xml", 
      'title'=>"sousk.net", 'href'=> feed_url }
    
    = stylesheet_link_tag "letterhead/screen", :media=>'screen'
    
  %body
    #header
      %h1#title= @page_title ||= 'page title'

    #sidebar
      %h4 recent
      %ul
        - Entry.published.limit(8).each do |e|
          %li= link_to e.title, entry_perm_path(e)
      %h4 Like What You See?
      %ul#nav
        %li= link_to "Get the Feed", feed_url
      %h4 about
      %ul#colophon
        %li
          !
          = link_to 'Tumblr', 'http://t.sousk.net/'
          powered
        %li
          = link_to "Bill Israel", "http://cubicle17.com/"
          designed

    #content.autopagerize_page_element
      #messages
        #notice= flash[:notice]
        #error= flash[:error]
        #warn= flash[:warn]
      #contents
        = yield :layout

    #previous-next.autopagerize_insert_before
      / footer